server:
  port: 8081
spring:
  datasource:
    username: homework
    password: homeworking
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/homework?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true



sa-token:
  token-name: token
  timeout: 3600